// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMIpaXwRwNVta7OXRvpJ8G2GJnh3JPKM',
    appId: '1:770224217348:web:8df3873d57585d8d284451',
    messagingSenderId: '770224217348',
    projectId: 'attendence-8c08c',
    authDomain: 'attendence-8c08c.firebaseapp.com',
    databaseURL: 'https://attendence-8c08c-default-rtdb.firebaseio.com',
    storageBucket: 'attendence-8c08c.appspot.com',
    measurementId: 'G-V0JMH1ZGFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJF0UldFGj62GI6xQaycoXtd4wMrRJtg',
    appId: '1:770224217348:android:dead66ff8993c62e284451',
    messagingSenderId: '770224217348',
    projectId: 'attendence-8c08c',
    databaseURL: 'https://attendence-8c08c-default-rtdb.firebaseio.com',
    storageBucket: 'attendence-8c08c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJGGMwvIv2hn9xB2w9acxnslnKWoo2UY',
    appId: '1:770224217348:ios:f84044bc1499167c284451',
    messagingSenderId: '770224217348',
    projectId: 'attendence-8c08c',
    databaseURL: 'https://attendence-8c08c-default-rtdb.firebaseio.com',
    storageBucket: 'attendence-8c08c.appspot.com',
    iosClientId: '770224217348-r9qrvnaj4hmciqpma6iqt8ak8iloiqo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJGGMwvIv2hn9xB2w9acxnslnKWoo2UY',
    appId: '1:770224217348:ios:92954ae8c4658619284451',
    messagingSenderId: '770224217348',
    projectId: 'attendence-8c08c',
    databaseURL: 'https://attendence-8c08c-default-rtdb.firebaseio.com',
    storageBucket: 'attendence-8c08c.appspot.com',
    iosClientId: '770224217348-iepknh62ojhbn88ttac9rhguneco2sv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
